### PR TITLE
Refined handling of entity ownership.

### LINKED ISSUE #53: Update handling for entites and 'notify own'
If somebody other than the node's author edits a node, the current logic of `notify_own_actions` doesn't work, since the logic uses `::getOwnerId`. The `RevisionLogInterface` provides a more nuanced method: `::getRevisionUser()`.

I propose updating the logic in `Subscribers::getSubscribers` to utilize that logic for node entities, and fall back to the current logic for non-revisionable entities.

### PR DESCRIPTION
**Pull request by jhedstrom**
- Better detection of entity ownership for entities implementing
  RevisionLogInterface.
- Fixes #53

### CODE REVIEW

**Comment by jhedstrom** [comment]
This change will require `8.2.x`+, but that should be ok, as [8.1.x is no longer supported](https://www.drupal.org/core/release-cycle-overview).

File: src/Subscribers.php [hunk 1]
```diff
@@ -291,6 +292,30 @@ public function getSubscribers(EntityInterface $entity, MessageInterface $messag
...
+   *
+   * @param \Drupal\Core\Entity\EntityInterface $entity
+   *   The entity to check ownership of.
+   * @param int $uid
+   *   The user ID to check for ownership.
+   *
+   * @return bool
+   *   Returns TRUE if the entity is owned by the given user ID.
+   */
+  protected function isEntityOwner(EntityInterface $entity, $uid) {
```
Comment (amitaibu) [inline src/Subscribers.php:305]: That seems to be useful also in og. shouldn't it live in core?

Comment (jhedstrom) [reply src/Subscribers.php:305]: Potentially. It might be helpful in the [workflow initiative](https://www.drupal.org/node/2721129)...
